-- MySQL Script generated by MySQL Workbench
-- Fri Jul  5 17:35:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `books` DEFAULT CHARACTER SET utf8 ;
USE `books` ;

-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `books`.`Role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(25) NOT NULL,
  `type_user` VARCHAR(20) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `books`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NULL,
  `surname` VARCHAR(25) NULL,
  `sex` VARCHAR(8) NULL,
  `dateOfBirth` DATE NULL,
  `address` VARCHAR(50) NULL,
  `phone` VARCHAR(15) NULL,
  `Role_idRole` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE,
  INDEX `fk_User_Role1_idx` (`Role_idRole` ASC) VISIBLE,
  CONSTRAINT `fk_User_Role1`
    FOREIGN KEY (`Role_idRole`)
    REFERENCES `mydb`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `books`.`Books` (
  `idBooks` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `author` VARCHAR(50) NULL,
  `price` DECIMAL(2) NULL,
  `datePublishing` DATE NULL,
  `namePublishing` VARCHAR(35) NULL,
  `dateArrival` DATE NULL,
  `dateCancellation` DATE NULL,
  `countPages` INT NULL,
  `countCopies` INT NULL,
  PRIMARY KEY (`idBooks`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `books`.`user_books` (
  `iduser_books` INT NOT NULL AUTO_INCREMENT,
  `User_idUser` INT NOT NULL,
  `Books_idBooks` INT NOT NULL,
  PRIMARY KEY (`iduser_books`),
  INDEX `fk_user_books_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_user_books_Books1_idx` (`Books_idBooks` ASC) VISIBLE,
  CONSTRAINT `fk_user_books_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_books_Books1`
    FOREIGN KEY (`Books_idBooks`)
    REFERENCES `mydb`.`Books` (`idBooks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `books`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `typeCategory` VARCHAR(30) NULL,
  `genre` VARCHAR(30) NULL,
  `language` VARCHAR(20) NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `books`.`Book_category` (
  `idBook_category` INT NOT NULL AUTO_INCREMENT,
  `Category_idCategory` INT NOT NULL,
  `Books_idBooks` INT NOT NULL,
  PRIMARY KEY (`idBook_category`),
  INDEX `fk_Book_category_Category1_idx` (`Category_idCategory` ASC) VISIBLE,
  INDEX `fk_Book_category_Books1_idx` (`Books_idBooks` ASC) VISIBLE,
  CONSTRAINT `fk_Book_category_Category1`
    FOREIGN KEY (`Category_idCategory`)
    REFERENCES `mydb`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_category_Books1`
    FOREIGN KEY (`Books_idBooks`)
    REFERENCES `mydb`.`Books` (`idBooks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from Users;